# Importer le module Active Directory
Import-Module ActiveDirectory

# Définir le domaine et l'OU où l'utilisateur sera créé
$domain = "alphatech.local"
$ouBase = "OU=Utilisateurs,DC=alphatech,DC=local"


# Liste des utilisateurs
$users = @(
@{Name="Thomas Kireche"; DisplayName="KIRECHE Thomas"; GivenName="Thomas"; Surname="Kireche"; SamAccountName="thomas.kireche"; UserPrincipalName="thomas.kireche@alphatech.local"; EmailAddress="thomas.kireche@alphatech.local"; Department="IT"; Title="Chef de projet en infrastructure cloud"; TelephoneNumber="+33 7 56 43 89 10"; StreetAddress="15 Rue du Gros Horloge, Rouen"; POBox="Boîte 17"; PostalCode="76000"; StateOrProvince="Seine-Maritime"; Country="FR"; FullName="Thomas Kireche"; Initials="TK"}, 
@{Name="Harry Potter"; DisplayName="POTTER Harry"; GivenName="Harry"; Surname="Potter"; SamAccountName="harry.potter"; UserPrincipalName="harry.potter@alphatech.local"; EmailAddress="harry.potter@alphatech.local"; Department="R&D"; Title="Ingénieur IoT"; TelephoneNumber="+33 5 97 43 97 71"; StreetAddress="58 Rue de Paris, Le Havre"; POBox="Boîte 19"; PostalCode="76600"; StateOrProvince="Seine-Maritime"; Country="FR"; FullName="Harry Potter"; Initials="HP"}, 
@{Name="Hermione Granger"; DisplayName="GRANGER Hermione"; GivenName="Hermione"; Surname="Granger"; SamAccountName="hermione.granger"; UserPrincipalName="hermione.granger@alphatech.local"; EmailAddress="hermione.granger@alphatech.local"; Department="Direction"; Title="CTO"; TelephoneNumber="+33 6 11 45 23 78"; StreetAddress="92 Avenue de Paris, Saint-Lô"; POBox="Boîte 5"; PostalCode="50000"; StateOrProvince="Manche"; Country="FR"; FullName="Hermione Granger"; Initials="HG"}, 
@{Name="Paul Atreides"; DisplayName="ATREIDES Paul"; GivenName="Paul"; Surname="Atreides"; SamAccountName="paul.atreides"; UserPrincipalName="paul.atreides@alphatech.local"; EmailAddress="paul.atreides@alphatech.local"; Department="R&D"; Title="Architecte système"; TelephoneNumber="+33 7 81 56 34 12"; StreetAddress="42 Place Napoléon, Cherbourg"; POBox="Boîte 22"; PostalCode="50100"; StateOrProvince="Manche"; Country="FR"; FullName="Paul Atreides"; Initials="PA"}, 
@{Name="Duncan Idaho"; DisplayName="IDAHO Duncan"; GivenName="Duncan"; Surname="Idaho"; SamAccountName="duncan.idaho"; UserPrincipalName="duncan.idaho@alphatech.local"; EmailAddress="duncan.idaho@alphatech.local"; Department="Production"; Title="Responsable production"; TelephoneNumber="+33 6 96 48 38 09"; StreetAddress="76 Boulevard Pasteur, Evreux"; POBox="Boîte 24"; PostalCode="27000"; StateOrProvince="Eure"; Country="FR"; FullName="Duncan Idaho"; Initials="DI"}, 
@{Name="Severus Snape"; DisplayName="SNAPE Severus"; GivenName="Severus"; Surname="Snape"; SamAccountName="severus.snape"; UserPrincipalName="severus.snape@alphatech.local"; EmailAddress="severus.snape@alphatech.local"; Department="Gestion"; Title="Responsable des finances"; TelephoneNumber="+33 5 22 78 44 35"; StreetAddress="18 Rue Jeanne d'Arc, Rouen"; POBox="Boîte 13"; PostalCode="76000"; StateOrProvince="Seine-Maritime"; Country="FR"; FullName="Severus Snape"; Initials="SS"}, 
@{Name="Albus Dumbledore"; DisplayName="DUMBLEDORE Albus"; GivenName="Albus"; Surname="Dumbledore"; SamAccountName="albus.dumbledore"; UserPrincipalName="albus.dumbledore@alphatech.local"; EmailAddress="albus.dumbledore@alphatech.local"; Department="Direction"; Title="CEO"; TelephoneNumber="+33 7 44 12 89 56"; StreetAddress="55 Place du Vieux-Marché, Rouen"; POBox="Boîte 36"; PostalCode="76000"; StateOrProvince="Seine-Maritime"; Country="FR"; FullName="Albus Dumbledore"; Initials="AD"}, 
@{Name="Chani Kynes"; DisplayName="KYNES Chani"; GivenName="Chani"; Surname="Kynes"; SamAccountName="chani.kynes"; UserPrincipalName="chani.kynes@alphatech.local"; EmailAddress="chani.kynes@alphatech.local"; Department="IT"; Title="Analyste réseau"; TelephoneNumber="+33 6 22 45 33 67"; StreetAddress="20 Rue du Dr Oursel, Evreux"; POBox="Boîte 18"; PostalCode="27000"; StateOrProvince="Eure"; Country="FR"; FullName="Chani Kynes"; Initials="CK"}, @{Name="Feyd-Rautha Harkonnen"; DisplayName="HARKONNEN Feyd-Rautha"; GivenName="Feyd-Rautha"; Surname="Harkonnen"; SamAccountName="feyd.harkonnen"; UserPrincipalName="feyd.harkonnen@alphatech.local"; EmailAddress="feyd.harkonnen@alphatech.local"; Department="Commerciaux"; Title="Commercial"; TelephoneNumber="+33 7 65 12 44 78"; StreetAddress="34 Rue de la République, Caen"; POBox="Boîte 9"; PostalCode="14000"; StateOrProvince="Calvados"; Country="FR"; FullName="Feyd-Rautha Harkonnen"; Initials="FH"}, 
@{Name="Gurney Halleck"; DisplayName="HALLECK Gurney"; GivenName="Gurney"; Surname="Halleck"; SamAccountName="gurney.halleck"; UserPrincipalName="gurney.halleck@alphatech.local"; EmailAddress="gurney.halleck@alphatech.local"; Department="Production"; Title="Technicien de production"; TelephoneNumber="+33 6 34 78 56 22"; StreetAddress="83 Rue Victor Hugo, Evreux"; POBox="Boîte 6"; PostalCode="27000"; StateOrProvince="Eure"; Country="FR"; FullName="Gurney Halleck"; Initials="GH"},
@{Name="Minerva McGonagall"; DisplayName="MCGONAGALL Minerva"; GivenName="Minerva"; Surname="McGonagall"; SamAccountName="minerva.mcgonagall"; UserPrincipalName="minerva.mcgonagall@alphatech.local"; EmailAddress="minerva.mcgonagall@alphatech.local"; Department="Direction"; Title="Directrice adjointe"; TelephoneNumber="+33 5 33 72 28 06"; StreetAddress="38 Rue de Verdun, Evreux"; POBox="Boîte 29"; PostalCode="27000"; StateOrProvince="Eure"; Country="FR"; FullName="Minerva McGonagall"; Initials="MM"}, 
@{Name="Leto Atreides"; DisplayName="ATREIDES Leto"; GivenName="Leto"; Surname="Atreides"; SamAccountName="leto.atreides"; UserPrincipalName="leto.atreides@alphatech.local"; EmailAddress="leto.atreides@alphatech.local"; Department="R&D"; Title="Responsable de recherche"; TelephoneNumber="+33 6 55 34 12 49"; StreetAddress="14 Boulevard Félix Amiot, Cherbourg"; POBox="Boîte 31"; PostalCode="50100"; StateOrProvince="Manche"; Country="FR"; FullName="Leto Atreides"; Initials="LA"}, 
@{Name="Luna Lovegood"; DisplayName="LOVEGOOD Luna"; GivenName="Luna"; Surname="Lovegood"; SamAccountName="luna.lovegood"; UserPrincipalName="luna.lovegood@alphatech.local"; EmailAddress="luna.lovegood@alphatech.local"; Department="Commerciaux"; Title="Assistante commerciale"; TelephoneNumber="+33 7 89 56 23 44"; StreetAddress="9 Place Napoléon, Cherbourg"; POBox="Boîte 14"; PostalCode="50100"; StateOrProvince="Manche"; Country="FR"; FullName="Luna Lovegood"; Initials="LL"}, 
@{Name="Vladimir Harkonnen"; DisplayName="HARKONNEN Vladimir"; GivenName="Vladimir"; Surname="Harkonnen"; SamAccountName="vladimir.harkonnen"; UserPrincipalName="vladimir.harkonnen@alphatech.local"; EmailAddress="vladimir.harkonnen@alphatech.local"; Department="Gestion"; Title="Contrôleur financier"; TelephoneNumber="+33 5 99 22 47 56"; StreetAddress="48 Rue François La Vieille, Cherbourg"; POBox="Boîte 40"; PostalCode="50100"; StateOrProvince="Manche"; Country="FR"; FullName="Vladimir Harkonnen"; Initials="VH"}, 
@{Name="Ginny Weasley"; DisplayName="WEASLEY Ginny"; GivenName="Ginny"; Surname="Weasley"; SamAccountName="ginny.weasley"; UserPrincipalName="ginny.weasley@alphatech.local"; EmailAddress="ginny.weasley@alphatech.local"; Department="Production"; Title="Opératrice de production"; TelephoneNumber="+33 6 43 89 76 22"; StreetAddress="60 Rue de la Poterne, Saint-Lô"; POBox="Boîte 23"; PostalCode="50000"; StateOrProvince="Manche"; Country="FR"; FullName="Ginny Weasley"; Initials="GW"} ,
@{Name="Rabban Harkonnen"; DisplayName="HARKONNEN Rabban"; GivenName="Rabban"; Surname="Harkonnen"; SamAccountName="rabban.harkonnen"; UserPrincipalName="rabban.harkonnen@alphatech.local"; EmailAddress="rabban.harkonnen@alphatech.local"; Department="Commerciaux"; Title="Commercial senior"; TelephoneNumber="+33 7 67 89 45 12"; StreetAddress="10 Boulevard de la Dollée, Saint-Lô"; POBox="Boîte 12"; PostalCode="50000"; StateOrProvince="Manche"; Country="FR"; FullName="Rabban Harkonnen"; Initials="RH"}, 
@{Name="Neville Longbottom"; DisplayName="LONGBOTTOM Neville"; GivenName="Neville"; Surname="Longbottom"; SamAccountName="neville.longbottom"; UserPrincipalName="neville.longbottom@alphatech.local"; EmailAddress="neville.longbottom@alphatech.local"; Department="IT"; Title="Technicien support informatique"; TelephoneNumber="+33 6 12 78 55 33"; StreetAddress="21 Avenue Pasteur, Rouen"; POBox="Boîte 30"; PostalCode="76000"; StateOrProvince="Seine-Maritime"; Country="FR"; FullName="Neville Longbottom"; Initials="NL"}, 
@{Name="Baron Harkonnen"; DisplayName="HARKONNEN Baron"; GivenName="Baron"; Surname="Harkonnen"; SamAccountName="baron.harkonnen"; UserPrincipalName="baron.harkonnen@alphatech.local"; EmailAddress="baron.harkonnen@alphatech.local"; Department="Direction"; Title="Consultant"; TelephoneNumber="+33 5 45 67 78 92"; StreetAddress="67 Rue des Carmes, Rouen"; POBox="Boîte 4"; PostalCode="76000"; StateOrProvince="Seine-Maritime"; Country="FR"; FullName="Baron Harkonnen"; Initials="BH"},
 @{Name="Bellatrix Lestrange"; DisplayName="LESTRANGE Bellatrix"; GivenName="Bellatrix"; Surname="Lestrange"; SamAccountName="bellatrix.lestrange"; UserPrincipalName="bellatrix.lestrange@alphatech.local"; EmailAddress="bellatrix.lestrange@alphatech.local"; Department="Gestion"; Title="Auditeur financier"; TelephoneNumber="+33 7 77 55 22 11"; StreetAddress="32 Place du Champ de Mars, Saint-Lô"; POBox="Boîte 28"; PostalCode="50000"; StateOrProvince="Manche"; Country="FR"; FullName="Bellatrix Lestrange"; Initials="BL"}, 
@{Name="Tony Stark"; DisplayName="STARK Tony"; GivenName="Tony"; Surname="Stark"; SamAccountName="tony.stark"; UserPrincipalName="tony.stark@alphatech.local"; EmailAddress="tony.stark@alphatech.local"; Department="Direction"; Title="Directeur général et responsable R&D"; TelephoneNumber="+33 7 88 23 67 45"; StreetAddress="58 Avenue Foch, Le Havre"; POBox="Boîte 38"; PostalCode="76600"; StateOrProvince="Seine-Maritime"; Country="FR"; FullName="Tony Stark"; Initials="TS"}, @{Name="Steve Rogers"; DisplayName="ROGERS Steve"; GivenName="Steve"; Surname="Rogers"; SamAccountName="steve.rogers"; UserPrincipalName="steve.rogers@alphatech.local"; EmailAddress="steve.rogers@alphatech.local"; Department="Production"; Title="Responsable de la production des drones"; TelephoneNumber="+33 6 45 78 89 12"; StreetAddress="90 Rue de Verdun, Evreux"; POBox="Boîte 38"; PostalCode="27000"; StateOrProvince="Eure"; Country="FR"; FullName="Steve Rogers"; Initials="SR"}, @{Name="Natasha Romanoff"; DisplayName="ROMANOFF Natasha"; GivenName="Natasha"; Surname="Romanoff"; SamAccountName="natasha.romanoff"; UserPrincipalName="natasha.romanoff@alphatech.local"; EmailAddress="natasha.romanoff@alphatech.local"; Department="IT"; Title="Responsable sécurité et protection des données"; TelephoneNumber="+33 7 63 45 89 23"; StreetAddress="70 Rue de Bayeux, Caen"; POBox="Boîte 20"; PostalCode="14000"; StateOrProvince="Calvados"; Country="FR"; FullName="Natasha Romanoff"; Initials="NR"}, 
@{Name="Stephen Strange"; DisplayName="STRANGE Stephen"; GivenName="Stephen"; Surname="Strange"; SamAccountName="stephen.strange"; UserPrincipalName="stephen.strange@alphatech.local"; EmailAddress="stephen.strange@alphatech.local"; Department="Direction"; Title="Consultant stratégie et développement"; TelephoneNumber="+33 6 34 56 23 78"; StreetAddress="62 Rue de Paris, Le Havre"; POBox="Boîte 41"; PostalCode="76600"; StateOrProvince="Seine-Maritime"; Country="FR"; FullName="Stephen Strange"; Initials="SS"}, 
@{Name="Wong"; DisplayName="WONG"; GivenName="Wong"; Surname=""; SamAccountName="wong"; UserPrincipalName="wong@alphatech.local"; EmailAddress="wong@alphatech.local"; Department="IT"; Title="Responsable des infrastructures informatiques"; TelephoneNumber="+33 7 22 45 67 89"; StreetAddress="15 Rue du Gros Horloge, Rouen"; POBox="Boîte 17"; PostalCode="76000"; StateOrProvince="Seine-Maritime"; Country="FR"; FullName="Wong"; Initials="W"}, 
@{Name="Nick Fury"; DisplayName="FURY Nick"; GivenName="Nick"; Surname="Fury"; SamAccountName="nick.fury"; UserPrincipalName="nick.fury@alphatech.local"; EmailAddress="nick.fury@alphatech.local"; Department="IT"; Title="Responsable de la cybersécurité et de l'intelligence"; TelephoneNumber="+33 7 23 45 67 89"; StreetAddress="89 Rue Victor Hugo, Le Havre"; POBox="Boîte 27"; PostalCode="76600"; StateOrProvince="Seine-Maritime"; Country="FR"; FullName="Nick Fury"; Initials="NF"}, @{Name="James Rhodes"; DisplayName="RHODES James"; GivenName="James"; Surname="Rhodes"; SamAccountName="james.rhodes"; UserPrincipalName="james.rhodes@alphatech.local"; EmailAddress="james.rhodes@alphatech.local"; Department="Direction"; Title="Directeur des opérations"; TelephoneNumber="+33 6 78 45 22 67"; StreetAddress="83 Place du Champ de Mars, Saint-Lô"; POBox="Boîte 4"; PostalCode="50000"; StateOrProvince="Manche"; Country="FR"; FullName="James Rhodes"; Initials="JR"}, 
@{Name="Rocket Raccoon"; DisplayName="RACCOON Rocket"; GivenName="Rocket"; Surname="Raccoon"; SamAccountName="rocket.raccoon"; UserPrincipalName="rocket.raccoon@alphatech.local"; EmailAddress="rocket.raccoon@alphatech.local"; Department="R&D"; Title="Ingénieur en armement des drones"; TelephoneNumber="+33 6 67 88 99 00"; StreetAddress="48 Place Napoléon, Cherbourg"; POBox="Boîte 44"; PostalCode="50100"; StateOrProvince="Manche"; Country="FR"; FullName="Rocket Raccoon"; Initials="RR"}, @{Name="Scott Lang"; DisplayName="LANG Scott"; GivenName="Scott"; Surname="Lang"; SamAccountName="scott.lang"; UserPrincipalName="scott.lang@alphatech.local"; EmailAddress="scott.lang@alphatech.local"; Department="R&D"; Title="Technicien spécialiste des capteurs"; TelephoneNumber="+33 7 34 78 56 12"; StreetAddress="34 Avenue de Normandie, Cherbourg"; POBox="Boîte 13"; PostalCode="50100"; StateOrProvince="Manche"; Country="FR"; FullName="Scott Lang"; Initials="SL"},
 @{Name="Sam Wilson"; DisplayName="WILSON Sam"; GivenName="Sam"; Surname="Wilson"; SamAccountName="sam.wilson"; UserPrincipalName="sam.wilson@alphatech.local"; EmailAddress="sam.wilson@alphatech.local"; Department="Commerciaux"; Title="Responsable des ventes régionales"; TelephoneNumber="+33 6 22 33 44 55"; StreetAddress="47 Chemin Vert, Caen"; POBox="Boîte 12"; PostalCode="14000"; StateOrProvince="Calvados"; Country="FR"; FullName="Sam Wilson"; Initials="SW"} )  

# Créer chaque utilisateur sous l'OU Utilisateurs
foreach ($user in $users) {
    $userPath = "$ouBase"
    
    # Vérifier si l'utilisateur existe déjà
    if (-not (Get-ADUser -Filter { SamAccountName -eq '$($user.SamAccountName)' } -SearchBase $ouBase -ErrorAction SilentlyContinue)) {
        # Créer l'utilisateur
        New-ADUser -Name $user.Name -GivenName $user.GivenName -Surname $user.Surname -SamAccountName $user.SamAccountName -UserPrincipalName $user.UserPrincipalName -Path $userPath -DisplayName $user.DisplayName -EmailAddress $user.EmailAddress -Department $user.Department -Title $user.Title -OfficePhone $user.TelephoneNumber -StreetAddress $user.StreetAddress -POBox $user.POBox -PostalCode $user.PostalCode -Country $user.Country -Initials $user.Initials -AccountPassword (ConvertTo-SecureString "Password123!" -AsPlainText -Force) -Enabled $true -Description "Poste : $($user.Title), Service : $($user.Department)"
      
        Write-Output "Utilisateur $($user.Name) créé avec succès. Utilisateur ajouté au groupe $($user.Department) et à l'OU Utilisateurs."
    }
    else {
        Write-Output "Utilisateur $($user.Name) existe déjà."
        } # Ajouter l'utilisateur au groupe correspondant

    Start-Sleep -Seconds 2
    Add-ADGroupMember -Identity $user.Department -Members $user.SamAccountName
    
    Write-Output "Utilisateur $($user.DisplayName) créé et ajouté au groupe $($user.Department)"
}
